"""Constants for the Atmoce + Indevolt HEMS integration."""

from __future__ import annotations

DOMAIN = "ha_atmoce_indevolt"
PLATFORMS = ["sensor", "select", "number", "switch", "button"]

CONF_ATMOCE_HOST = "atmoce_host"
CONF_ATMOCE_PORT = "atmoce_port"
CONF_ATMOCE_PANEL_COUNT = "atmoce_panel_count"
CONF_INDEVOLT_HOST = "indevolt_host"
CONF_INDEVOLT_PORT = "indevolt_port"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_ATMOCE_HOST = "192.168.1.8"
DEFAULT_ATMOCE_PORT = 502
DEFAULT_INDEVOLT_PORT = 8080
DEFAULT_SCAN_INTERVAL = 30

ATMOCE_DEVICE = "atmoce_gateway"
INDEVOLT_DEVICE = "indevolt_storage"
HEMS_DEVICE = "hems_coordinator"

# Atmoce MG100 / MC100 gateway Modbus holding registers (see evcc atmoce template).
ATMOCE_REG_PV_POWER = 60069
ATMOCE_REG_BATTERY_POWER = 60071
ATMOCE_REG_GRID_POWER = 60073
ATMOCE_REG_GRID_VOLTAGE_A = 60089
ATMOCE_REG_GRID_VOLTAGE_B = 60091
ATMOCE_REG_GRID_VOLTAGE_C = 60093
ATMOCE_REG_GRID_CURRENT_A = 60090
ATMOCE_REG_GRID_CURRENT_B = 60092
ATMOCE_REG_GRID_CURRENT_C = 60094
ATMOCE_REG_BATTERY_SOC = 60095
ATMOCE_REG_PV_ENERGY_TOTAL = 60160
ATMOCE_REG_BATTERY_CHARGE_ENERGY_TOTAL = 60166
ATMOCE_REG_BATTERY_DISCHARGE_ENERGY_TOTAL = 60172
ATMOCE_REG_GRID_EXPORT_ENERGY_TOTAL = 60178
ATMOCE_REG_GRID_IMPORT_ENERGY_TOTAL = 60184

ATMOCE_REG_BATTERY_FORCE_CONTROL = 60310
ATMOCE_REG_BATTERY_FORCE_MODE = 60311
ATMOCE_REG_BATTERY_FORCE_TARGET_SOC = 60312
ATMOCE_REG_BATTERY_MAX_CHARGE_POWER = 60318
ATMOCE_REG_BATTERY_MAX_DISCHARGE_POWER = 60320
ATMOCE_REG_PV_MAX_POWER = 60322
ATMOCE_REG_GRID_MAX_IMPORT_POWER = 60326

# Indevolt OpenData cJSON points (SolidFlex / SF3000 family).
INDEVOLT_POINT_WORKING_MODE = 7101
INDEVOLT_POINT_RATED_CAPACITY = 142
INDEVOLT_POINT_GRID_CHARGING = 2618
INDEVOLT_POINT_INVERTER_INPUT_LIMIT = 11009
INDEVOLT_POINT_AC_INPUT_POWER = 2101
INDEVOLT_POINT_AC_OUTPUT_POWER = 2108
INDEVOLT_POINT_FEED_IN_LIMIT = 11010
INDEVOLT_POINT_MAX_AC_OUTPUT = 11011
INDEVOLT_POINT_BACKUP_SOC = 6105
INDEVOLT_POINT_AC_INPUT_ENERGY = 2107
INDEVOLT_POINT_AC_OUTPUT_ENERGY = 2104
INDEVOLT_POINT_BATTERY_POWER = 6000
INDEVOLT_POINT_BATTERY_STATE = 6001
INDEVOLT_POINT_BATTERY_SOC = 6002
INDEVOLT_POINT_GRID_VOLTAGE = 799
INDEVOLT_POINT_GRID_FREQUENCY = 800
INDEVOLT_POINT_METER_POWER = 7619
INDEVOLT_POINT_BYPASS_POWER = 667
INDEVOLT_POINT_PACK_SOC = {
    1: 9016,
    2: 9024,
    3: 9032,
    4: 9040,
    5: 9048,
}
INDEVOLT_POINT_PACK_TEMP = {
    1: 9022,
    2: 9030,
    3: 9038,
    4: 9046,
    5: 9054,
}

INDEVOLT_SET_WORKING_MODE = 47005
INDEVOLT_SET_RT_STATE = 47015
INDEVOLT_SET_RT_POWER = 47016
INDEVOLT_SET_RT_TARGET_SOC = 47017
INDEVOLT_SET_MAX_AC_OUTPUT = 1147
INDEVOLT_SET_FEED_IN_LIMIT = 1146
INDEVOLT_SET_GRID_CHARGING = 1143
INDEVOLT_SET_INVERTER_INPUT_LIMIT = 1138
INDEVOLT_SET_BACKUP_SOC = 1142
INDEVOLT_SET_BYPASS = 7266
INDEVOLT_SET_LED = 7265

INDEVOLT_MODE_SELF_CONSUMPTION = 1
INDEVOLT_MODE_REALTIME = 4
INDEVOLT_MODE_SCHEDULE = 5

INDEVOLT_RT_STANDBY = 0
INDEVOLT_RT_CHARGING = 1
INDEVOLT_RT_DISCHARGING = 2

INDEVOLT_BATTERY_STATE_STATIC = 1000
INDEVOLT_BATTERY_STATE_CHARGING = 1001
INDEVOLT_BATTERY_STATE_DISCHARGING = 1002

INDEVOLT_GRID_CHARGING_DISABLED = 1000
INDEVOLT_GRID_CHARGING_ENABLED = 1001

INDEVOLT_SENSOR_KEYS = (
    "pv_power",
    "grid_power",
    "grid_voltage_a",
    "grid_voltage_b",
    "grid_voltage_c",
    "grid_current_a",
    "grid_current_b",
    "grid_current_c",
    "pv_energy_total",
    "grid_import_energy_total",
    "grid_export_energy_total",
    "battery_soc",
    "battery_power",
    "indevolt_battery_soc",
    "indevolt_battery_power",
    "indevolt_battery_state",
    "indevolt_working_mode",
    "indevolt_ac_input_power",
    "indevolt_ac_output_power",
    "indevolt_rated_capacity",
    "indevolt_grid_voltage",
    "indevolt_grid_frequency",
    "indevolt_meter_power",
    "indevolt_bypass_power",
    "indevolt_ac_input_energy",
    "indevolt_ac_output_energy",
    "hems_pv_surplus",
    "hems_site_consumption",
    "hems_self_consumption_rate",
)
